sudo: required
dist: trusty
language: shell
services:
- docker
env:
  matrix:
  - STACK=cedar-14 IMAGE_TAG=heroku/cedar:14 PRIVATE_IMAGE_TAG=heroku/cedar-private:14
  - STACK=heroku-16 IMAGE_TAG=heroku/heroku:16 PRIVATE_IMAGE_TAG=heroku/heroku-private:16
  - STACK=heroku-18 IMAGE_TAG=heroku/heroku:18 PRIVATE_IMAGE_TAG=heroku/heroku-private:18
script:
- bin/build.sh $STACK $IMAGE_TAG $IMAGE_TAG-build
- |
  status="$(git status --porcelain)"
  if [[ -n "$status" ]]; then
    echo -e "Regenerated files differ from checked-in versions!\n${status}\n"
    git diff --exit-code
  fi
deploy:
  - provider: script
    script: bin/convert-and-publish-to-heroku.sh
    on:
      tags: true
  - provider: script
    script: sh bin/publish-to-dockerhub.sh
    on:
      all_branches: true
